### PR TITLE
Adding usage instruction for using model output for built-in algorithms

### PR DESCRIPTION
**Pull request by mriccia**
This PR adds usage instruction for models built using SageMaker Built-in algorithms.

So far I have only added Linear Learner and added some more context to the XGBoost instruction.

Ideally I would like to add instructions for all the SageMaker built-in algorithms., please let me know if that would be welcome and any feedback on this.

### CODE REVIEW

**Comment by bradsev** [comment]
Thanks Michele. 
This looks really useful. I will test and consult with our product team. 
Instructions for the other build-in algorithms is very welcome.
Cheers, Roald 
(I have been to Woking BTW.)

**Comment by mriccia** [comment]
Great thank you Roald, appreciate the feedback, I will keep working on the other built-in algorithms with another colleague in the UK.
(Let me know if you happen to be in Woking again :) )

**Comment by aaronmarkham** [comment]
Can you fix the conflicts and merge this?

**Comment by aaronmarkham** [comment]
@bradsev ^

**Comment by aws-rbs** [comment]
This has been fixed.

**Pull request closed without merging**
