### PR TITLE
Update clarify-post-training-bias-metric-dcr.md

### PR DESCRIPTION
**Pull request by jane-delaney**
This seems to be the wrong way around. If there are more observed rejections than predicted rejections for facet d then the bias is against facet a not facet d.

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by aws-rbs — COMMENTED** [review]
Thanks or the careful reading. This edit is correct for the example, but not for the interpretation of positive and negative values. I am going to make the changes in the doc and they will go live 3/15/2022.

**Comment by jane-delaney** [comment]
Are you sure about the interpretation of positive and negative values? If the ratio of the observed number of rejections compared to predicted rejections for one facet is greater than another facet, it means there are more actual rejections than predicted rejections so indicates bias in favour of the first facet and against the second facet?

**Comment by aws-rbs** [comment]
Ah, thanks for the follow up. Now I am amused by reading something I worked on over a year ago and seeing the possible ambiguity when taken out of context. I think you are correct about the interpretation of positive and negative values. But the confusion on my part was the assumption about the source of truth. Here is the final sentence in the introduction: "For example, if there were more rejections (a negative outcome) for loan applications for a middle-aged group (facet a) than predicted by the model based on qualifications as compared to the facet containing other age groups (facet d), this might indicate potential bias in the way loans were rejected." No comment about quality of the bias. When I read this, I took the model as the more objective arbiter as it was based on the qualification data and I considered the observed data of rejections as the potential source of bias. So a larger ratio of the observed number of rejections compared to predicted rejections for facet d would indicate a potential bias against the qualified applicants from facet d was observed. But this is a metric that is assessing model bias (not bias in the data) and assumes the observed data is the source of truth. So this is rather an under prediction of rejections and is a bias in favor of facet d (as compared to a in the metric when its ratio is less). So thanks again. I think this metric could actually function as data bias metric if you were confident in the objectivity of your model. But not in this context. So thanks again for making me think harder. (Did not get to this earlier as I was on vacation for most of the last month.) Cheers, RBS

**Comment by aws-rbs** [comment]
I am going to merge this here. I am making some additional clarifying remarks that preserve your edits that will be refreshed on GitHub next Friday.

**Comment by jane-delaney** [comment]
Thanks for the explanation, I know what it's like to return to something you haven't worked on in ages and try to remember the details. Glad it makes sense anyway. The idea of using this to analyse bias in the data itself is interesting too.

**Pull request merged**
